version: '2'
services:
  ap:
    image: base 
    ports: 
      - "80:80"
      - "8080:8080"
    working_dir: "/code"
    #volumes_from:
    #  - code
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    tty: true # to keep it alive, however this triggers http error exception on docker-compose up(container still running ,though)

  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  redis: # todo: persistence
    image: redis
    ports:
      - "6379:6379"

 