version: '2'
services:
  postgresql:
    image: sameersbn/postgresql:9.4-3
    container_name: postgresql
    environment:
      - DB_NAME=gitlabhq_production
      - DB_USER=gitlab
      - DB_PASS=password
    volumes:
      - /srv/docker/gitlab/postgresql:/var/lib/postgresql:rw
    tty: true

  redisio:
    image: sameersbn/redis:latest
    container_name: redisio
   
  gitlab:
    image: sameersbn/gitlab:8.0.2 
    container_name: gitlab
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      - GITLAB_HOST="192.168.121.68"
      - GITLAB_PORT="10080"
      - GITLAB_SECRETS_DB_KEY_BASE="long-and-random-alpha-numeric-string"
    volumes:
      - /srv/docker/gitlab/gitlab:/home/git/data:rw
    depends_on:
      - postgresql
      - redisio
    links:
      - postgresql
      - redisio
    tty: true
   
