version: '2'
services:
  postgresql:
    image: sameersbn/postgresql:9.4-3
    #container_name: gitlab-postgresql
    environment:
      - DB_NAME=gitlabhq_production
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_EXTENSION=pq_trgm
    volumes:
      - /srv/docker/gitlab/postgresql:/var/lib/postgresql:rw
    tty: true
    entrypoint: /start

  redis:
    image: sameersbn/redis:latest
    entrypoint: /sbin/entrypoint.sh
    #container_name: gitlab-redisio
   
  gitlab:
    image: sameersbn/gitlab:8.0.2 
    #container_name: gitlab
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      - GITLAB_HOST=192.168.121.68
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
    volumes:
      - /srv/docker/gitlab/gitlab:/home/git/data:rw
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql:postgresql
      - redis:redisio
    tty: true
    entrypoint: /sbin/entrypoint.sh

   
